### PR TITLE
Add support for 1.4 to cyclonedx-bom

### PR DESCRIPTION
**Pull request by justahero**
This PR is based on #399. @tokcum, first of all thanks for your contribution & also your patience. @lfrancke asked me to help bring your PR over the finish line. In this PR I also integrated the feedback given by @Shnatsel in #399. I hope that is in your interest.

In this PR I changed a few things slightly, but otherwise tried to keep the commit history as consistent as possible. The following things have been updated or addressed.

* rebased with `main` to resolve merge conflicts. I advise to review these changes, when in doubt I checked against `main`.
* addressed all `todos` to the best of my understanding based on feedback by @Shnatsel
  * added validation for vulnerabilities
  * added error variant `BomError` to error types `JsonWriteError` & `XmlWriteError` in order to remove `.expect` calls in serialization
  * removed commented code
* removed the big test JSON sample files that increased the size of the PR to about 11Mb
  * a few commits have been squashed accordingly
  * this is an area where dedicated test files to highlight specific use cases may provide better value
* fixed a few invalid URLs in the sample JSON files (e.g. trailing text or invalid encoded sequence `\u0026`)

There were a few TODOs left that might be good candidates to be addressed on their own

* [`cyclonedx-bom::models::Component`](https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/main/cyclonedx-bom/src/models/component.rs#L49) changed its `version` field to be `Option<NormalizedString>`, see [this comment](https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/399/files#diff-c7815a1123d905af77fe6e77044c9f277306d43e46272cb4f8417837bd61a6bcR48)
* [`cyclonedx-bom::models::VulnerabilityRating impl`](https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/399/files#diff-104c3655a4805410b7b465b76b6d1dd9a1fd756c894ed1f4a45f0d523ea1a453R62) had the comment `todo: how to decide what to validate, check this`

Please feel free to review & give feedback. I'm certain I got a few things wrong or might have missed something important.

### CODE REVIEW

**Comment by lfrancke** [comment]
DCO is missing, could you add that?

**Review by Shnatsel — APPROVED** [review]
Looks good, merging. Thanks!

**Comment by ctron** [comment]
Could this be released already?

**Comment by Shnatsel** [comment]
We're looking to add 1.5 support before the end of the year and ship it as a single breaking change, rather than make two breaking changes in quick succession.

**Comment by ctron** [comment]
Ok, that's fair. Thanks for the update.

**Comment by nikstur** [comment]
> We're looking to add 1.5 support before the end of the year and ship it as a single breaking change, rather than make two breaking changes in quick succession.

@Shnatsel at this points, it's probably worthwhile to cut a new release, since 1.5 seems to be taking a little more time. What do you think?

**Comment by Shnatsel** [comment]
Yes, we will cut a new release sometime next week.

**Pull request merged**
