### PR TITLE
Fix PURL test failures, migrate `cyclonedx-bom` to `purl` crate

### LINKED ISSUE #636: Switch from `packageurl` to `purl` crate
Currently `cyclonedx-bom` relies on `packageurl` crate, which does not support important fields such as qualifiers (e.g. `?vcs_url=...` so that we could encode repo URLs for git dependencies), and the last release of `packageurl` has been 2 years ago.

The `purl` crate is a lot more complete and is actively maintained. The maintainers aren't afraid of tackling [tough issues](https://github.com/phylum-dev/purl/issues/11) across the whole PURL ecosystem that [require changes to the spec](https://github.com/package-url/purl-spec/pull/261). (Naturally, spec authors ignore their PRs, but it's the thought that counts!)

`cargo cyclonedx` already depends on `purl` to compose the actual PURLs and then converts them to `packageurl` to feed them to `cyclonedx-bom`. We should migrate `cyclonedx-bom` itself to `purl` crate as well, since the `packageurl` is woefully insufficient even for our own use cases and that is not going to change anytime soon.

### LINKED ISSUE #745: `cargo cyclonedx` tests fail after upgrading to `purl` 0.1.3
The tests for `cargo cyclonedx` fail after upgrading `purl` from 0.1.2 to 0.1.3:
```
failures:

---- purl::tests::git_purl stdout ----
thread 'purl::tests::git_purl' panicked at cargo-cyclonedx/src/purl.rs:129:9:
assertion `left == right` failed
  left: "git%2Bhttps%3A%2F%2Fgithub.com%2Frust-secure-code%2Fcargo-auditable.git%40da85607fb1a09435d77288ccf05a92b2e8ec3f71"
 right: "git+https://github.com/rust-secure-code/cargo-auditable.git@da85607fb1a09435d77288ccf05a92b2e8ec3f71"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- purl::tests::local_package stdout ----
thread 'purl::tests::local_package' panicked at cargo-cyclonedx/src/purl.rs:223:9:
assertion `left == right` failed
  left: "file://%2Fhome%2Fshnatsel%2FCode%2Fcargo-cyclonedx%2Fcyclonedx-bom"
 right: "file:///home/shnatsel/Code/cargo-cyclonedx/cyclonedx-bom"

---- purl::tests::toplevel_package_with_subpath stdout ----
thread 'purl::tests::toplevel_package_with_subpath' panicked at cargo-cyclonedx/src/purl.rs:176:9:
assertion `left == right` failed
  left: "src/%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%D0%B8%D1%86%D0%B0/lib.rs"
 right: "src/кириллица/lib.rs"

---- purl::tests::workspace_package stdout ----
thread 'purl::tests::workspace_package' panicked at cargo-cyclonedx/src/purl.rs:199:9:
assertion `left == right` failed
  left: "file://..%2Fcyclonedx-bom"
 right: "file://../cyclonedx-bom"
```

### PR DESCRIPTION
**Pull request by Shnatsel**
### `cargo cyclonedx`

Drop our custom percent encoding machinery now that the `purl` crate implements this for us. This was [one hell of a rabbit hole](https://github.com/phylum-dev/purl/issues/11), and it is a testament to the quality of the `purl` crate that they are actually handling this nonsense correctly now.

Fixes #745

### `cyclonedx-bom`

Migrate from the very incomplete `packageurl` to the `purl` crate already used by `cargo cyclonedx`. We used to have two different PURL crates in the tree, this brings the number back to one. Also provide a more informative error message on validation errors.

Fixes #636

This is all still semver-compatible, because the `packageurl` crate was never actually exposed to the outside world. But this is a PR against main because I cannot be bothered to backport this.

### CODE REVIEW

**Comment by lfrancke** [comment]
Thank you for this. It looks good to me.

Should https://github.com/phylum-dev/purl/issues/11 be closed if it's handled now? 
They don't seem to have a changelog or release notes but I do see upstream commits on this.

**Comment by Shnatsel** [comment]
Good point, I closed the upstream issue.

**Comment by pombredanne** [comment]
@Shnatsel hey, can you tell me more about the purl vs. the packageurl crates? (My interest is as the creator of the PURL spec ;) )

**Comment by Shnatsel** [comment]
@pombredanne as of this PR, the `purl` crate was a lot more complete and had a lot more effort put into correctness. It is also actively maintained. For example, when I brought up strange percent encoding on their bug tracker, the authors investigated it in detail and eventually opened this PR against the spec: https://github.com/package-url/purl-spec/pull/261

(I'd appreciate if you could take a look at that PR, it's a major interoperability hazard)

Meanwhile the `packageurl` crate has been effectively abandoned for some time by the time this PR was opened. Since then @ctron has gotten commit rights and revived it, but I don't know what direction they're taking it in, or what its current state is.

**Pull request merged**
