### PR TITLE
add --version flag

### LINKED ISSUE #555: Add a "-V" / "--version" flag to print the current version

### PR DESCRIPTION
**Pull request by tshepang**
Closes #555

### CODE REVIEW

**Review by Shnatsel — APPROVED** [review]
Looks good, just needs sign-off: `git rebase HEAD~1 --signoff` and then `git push --force`. Thanks!

**Comment by tshepang** [comment]
oh, forgot

**Review by lfrancke — CHANGES_REQUESTED** [review]
The readme needs to be updated

**Review by Shnatsel — CHANGES_REQUESTED** [review]
Now that I tested it, this change made `cargo-cyclonedx --version` work, but what we need is `cargo-cyclonedx cyclonedx --version` because that is how our binary is called through Cargo.

The `--version` flag must be moved to the `cyclonedx` subcommand.

**Comment by Shnatsel** [comment]
I've opened a PR with all the changes requested here actually applied: #561

**Comment by tshepang** [comment]
thanks

**Pull request closed without merging**
