### PR TITLE
fix visibility of `HashValue`

### PR DESCRIPTION
**Pull request by jondot**
This enables to actually provide hashes

### CODE REVIEW

**Comment by lfrancke** [comment]
Could you add the DCO to your commit?

See here for details: https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/376/checks?check_run_id=11218823763

**Comment by Shnatsel** [comment]
The ability to write the hash is definitely required, but I don't think this is the way to do. I would prefer to expose a method that accepts a string and validates it, and only creates the hash struct if the string is actually valid for the supplied algorithm.

**Comment by Shnatsel** [comment]
Nevermind, I take that back. 

Introducing a type-level distinction between validated and non-validated data would be great, but would require a rather significant refactoring of the whole crate for consistency. It does not make sense to introduce it in some places but not others.

**Comment by lfrancke** [comment]
Validating hashes seems like a nice to have but definitely also not trivial to do and not sure if we even want to get into that...

**Comment by lfrancke** [comment]
See #519 for a new version of this.
I'm going to close this in favor of the new one.
Thank you for bringing it up!

**Pull request closed without merging**
